language: "node_js"
node_js:
  - 0.10
notifications:
  email: false
after_script:
- cat coverage/lcov.info | codeclimate
addons:
  code_climate:
    repo_token:
      secure: "XgsAylKB5ldlhkMWE1Oo4sWScc6rddjTpdQnol6Ijb0Gvkg2NHoxON+L42YKHZRMt3dX+sIrIIalVSyTVa1+ulSMM0uFrQ1TrSjHq3EYwIYOwxU/3S3yuKdy/lqUZuG1axQnFgr0H7YhrV1tWmWTQtiB7Ph6r9l8CTSewG5bmdE="
